version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:latest-fpm
    restart: unless-stopped
    volumes:
      - "./src:/var/www"
    working_dir: /var/www
    networks:
      - app-network
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - "./src:/var/www"
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - app-network
  db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "5306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
    - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local